######################################################################
# Automatically generated by qmake (2.01a) ?? 4? 21 16:13:34 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += imageIden.h public.h TQInputMethod.h
FORMS += imageIden.ui
SOURCES += imageIden.cpp main.cpp
LIBS += -L. -lTQInputMethod

